In [1]:
import pandas as pd

In [6]:
filepath = "adoption.csv"
df = pd.read_csv(filepath, sep=";")

In [7]:
df

,Name,Kind,Age,Breed,Vaccinated,Location,Gender,Neutered,Date found
0,Tobby,dog,4,chihuahua,yes,Graz,male,yes,05/01/2022
1,Sissy,cat,1,American Wirehair,yes,Vienna,female,yes,07/01/2022
2,Thystisshtys,snake,1,Hog Island Boa,no,Linz,male,no,10/01/2022
3,Slow Poke,turtle,20,Yellow-Bellied Slider,no,Vienna,male,no,12/01/2022
4,Smeagol,cat,7,Siberian,yes,Vienna,male,yes,14/01/2022
5,Mackenzie,dog,9,Boykin spaniel,yes,Linz,female,no,21/01/2022
6,Honey,guinea pig,1,Silkie Guinea Pig,yes,Linz,male,yes,25/01/2022
7,Kira,dog,2,Doberman pinscher,no,Linz,female,no,28/01/2022
8,Kiri,hedgehog,3,African Pygmy,no,Graz,female,yes,31/01/2022
9,Maverick,dog,5,Irish setter,yes,Salzburg,male,yes,07/02/2022
10,Triku,hedgehog,2,African Pygmy,no,Salzburg,male,yes,10/02/2022
11,Shanty,cat,2,Maine Coon,yes,Vienna,female,yes,15/02/2022
12,Violet,dog,2,Boxer,no,Innsbruck,female,no,17/02/2022
13,Beefcakes,hamster,1,Syrian Hamster,yes,Salzburg,female,yes,21/02/2022
14,Toulouse,cat,14,Norwegian Forest,no,Klagenfurt,male,yes,02/03/2022
15,Skylar,bird,2,Budgerigar,yes,Vienna,male,no,08/03/2022
16,Aurora,bird,2,Budgerigar,yes,Vienna,female,no,10/03/2022
17,Walter,dog,1,Boxer,no,Vienna,male,yes,15/03/2022
18,Daisy,cat,6,Egyptian Mau,no,Bregenz,female,no,21/03/2022
19,Sniffles,rabbit,2,American Fuzzy Lop,yes,Vienna,male,yes,22/03/2022
20,Rain,cat,8,Cornish Rex,yes,Graz,female,no,07/04/2022

In [70]:
def printMenu(df):
    print("------------------------------------------------------------------------------\n" + \
        "-----------------------WELCOME TO THE ADOPTION APP!!!---------------------------\n" + \
         "--------------------------------------------------------------------------------\n")
    while True:
        opt = input(
        "\n" + \
        "Select an option:\n" + \
        "1) Display all animals\n" + \
        "2) Display number of animals\n" + \
        "3) Display animal by Index\n" + \
        "4) Display animal by Kind\n" + \
        "5) Calculate average age\n" + \
        "6) Create new animal\n" + \
        "7) Edit animal\n" + \
        "8) Delete an animal\n" + \
        "9) Save file\n" + \
        "0) Exit\n\n" + \
        " Option:")
        if opt.isdigit():
            opt= int(opt)
            if opt == 0: 
                exitMenu()
                break
            elif opt == 1:
                printAllAnimals(df)
            elif opt == 2:
                countAnimals(df)
            elif opt == 3:
                index_n = int(input("Introduce index:"))
                printAnimal(df, index_n)
            elif opt == 4:
                kind = input("Introduce kind: (options: cat, dog, snake, hedgehog, rabbit, " + 
                             "turtle, guinea pig, hamster, bird): ")
                printAnimalKind(df, kind)
            elif opt == 5:
                calcAvg(df)
            elif opt == 6:
                df = createAnimal(df)
                print("New record was created!!!")
            elif opt == 7:
                index_n = int(input("Introduce index of Animal to edit: "))
                column = input("What would you like to edit? (Options: Name, Kind, Age, Breed," +
                               " Vaccinated, Location, Gender, Neutered or Date Found): ")
                new_value = input("Introduce new value: ")
                editAnimal(df, index_n, column, new_value)
                print("\n\n Record was editted!!! \n\n")
            elif opt == 8:
                index_n = int(input("introduce index of a animal to delete:"))
                deleteAnimal(df, index_n)
                print("\n\n Record was deleted \n\n")
            elif opt ==9:
                saveFile(df)
                print("Changes were saved to the file!")
            else: 
                print("Please introduce a valid number!!!")
        else:
            print("please introduce a number!!")

In [ ]:
printMenu(df)

------------------------------------------------------------------------------
-----------------------WELCOME TO THE ADOPTION APP!!!---------------------------
--------------------------------------------------------------------------------

 Option:uefef
please introduce a number!!
 Option:2
The number of animals is  21
 Option:5
Average Age is 4.52

In [24]:
def exitMenu():
    print("Thank you for using this cool app!")

In [26]:
def printAllAnimals(df):
    print(df.to_string())

In [28]:
def countAnimals(df):
    print("The number of animals is ", df.shape[0])

In [33]:
def printAnimal(df, index_animal ):
    print("\n\n")
    print(df.loc[[index_animal]].to_string())
    print("\n\n")

In [39]:
def printAnimalKind(df,kind):
    print("\n\n")
    print(df[df["kind"] == kind].to_string())
    print("\n\n")

In [42]:
def calcAvg(df):
    mean = round(df["Age"].mean(),2)
    print("Average Age is", mean)

In [44]:
def createAnimal(df):
    name = input("Name of the animal:")
    kind = input("What kind of animal is it?")
    age = int(input("Age of the animal: "))
    breed = input("What breed is it? ")
    vaccine = input("Is the animal vaccinated? (yes/no): ")
    location = input("Location of the animal: ")
    gender = input("Gender of the animal: ")
    neutered = input("Is the animal neutered? (yes/no): ")
    date_found = input("When was the animal found? (DD/MM/YYYY): ")
    new_df = pd.DataFrame(
            {'Name': name,
            'Kind':  kind,
            'Age': age,
            'Breed': breed,
            'Vaccinated': vaccine,
            'Location': location,
            'Gender':  gender,
            'Neutered': neutered,
            'Date found': date_found
            }, index=[0])
    df = pd.concat(df, new_df, ignore_index = True)

In [46]:
def editAnimal(df, index_n, column, new_value):
    df.loc[index, column] = new_value

In [47]:
def deleteAnimal(df, index):
    df = df.drop(labels=[index])
    return df

In [52]:
def saveFile(df):
    df.to_csv(file_name, mode = 'w+', index = False, header = True, sep = ";")